version: "3"

services:
  mongodb1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - 27017:27017
    volumes:
      - ./mongo1:/data/db

  mongodb2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    command: mongod --replSet rs0 --bind_ip_all --port 27018
    ports:
      - 27018:27018
    volumes:
      - ./mongo2:/data/db

  mongodb3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    command: mongod --replSet rs0 --bind_ip_all --port 27019
    ports:
      - 27019:27019
    volumes:
      - ./mongo3:/data/db


networks:
  default:
    name: mongoCluster
    # external: true    // docker network 미리 생성한 경우